/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Constructores.Constructor_Mi_empresa;
import Constructores.Constructor_Usuario;
import Controlador.Funciones_Entrada_Inventario;
import Controlador.Funciones_Generales;
import Controlador.Funciones_frm_factura;
import java.text.DecimalFormat;

/**
 *
 * @author Nestor1
 */
public class frm_Mi_Empresa extends javax.swing.JInternalFrame {

    Constructor_Usuario usuario_activo= new Constructor_Usuario();
    private String user= null;
    Constructor_Mi_empresa mi_empresa = new Constructor_Mi_empresa();
    DecimalFormat formateador = new DecimalFormat("###,###");
    /**
     * Creates new form frm_Producto
     */
    public frm_Mi_Empresa(Object usuario) {
        initComponents();
        user=usuario.toString();
        inicializar();
    }

    private void inicializar()
    {
        consultarDatosUsuario();
        consultarDatosMiEmpresa();
        promedioVentas();
        lbl_correo.setText(mi_empresa.getCorreo());
        lbl_fecha_resolucion.setText(mi_empresa.getResolucion_facturacion_fecha());
        lbl_gerente.setText(mi_empresa.getGerente());
        lbl_nit_empresa.setText(mi_empresa.getNit());
        lbl_nombre_empresa.setText(mi_empresa.getEmpresa());
        lbl_fecha_resolucion.setText(mi_empresa.getResolucion_facturacion_fecha());
        lbl_facturacion_desde.setText(mi_empresa.getResolucion_facturacion_desde());
        lbl_facturacion_hasta.setText(mi_empresa.getResolucion_facturacion_hasta());
        lbl_factura_actual.setText(String.valueOf(mi_empresa.getUltimaFactura()));
        lbl_regimen.setText(mi_empresa.getTipo_regimen_empresa());
        lbl_resolucion_fact.setText(mi_empresa.getResolucion());
    }
     private void consultarDatosUsuario()
    {
        Controlador.Funciones_Generales funciones_producto= new Funciones_Generales();
        usuario_activo=funciones_producto.usuario(user);
    }
      private void consultarDatosMiEmpresa() {
        Funciones_Generales fun = new Funciones_Generales();
        mi_empresa = fun.datosMiEmpresa(usuario_activo.getId_sucursal());
    }
      
      private void promedioVentas()
      {
          consultarDatosUsuario();
          consultarDatosMiEmpresa();
          Funciones_Generales fun = new Funciones_Generales();
          Funciones_Entrada_Inventario n = new Funciones_Entrada_Inventario();
          lbl_promedio_ventas_diaria.setText(formateador.format(fun.promedioVentasDiarias(mi_empresa.getId_empresa())));
          lbl_promedio_ventas_mensual.setText(formateador.format(fun.promedioVentasMensuales(mi_empresa.getId_empresa())));
          lbl_valor_inventario.setText((String) (n.funcionCuantoGanaciaInventario(usuario_activo.getId_sucursal())));
      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_nombre_empresa = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        lbl_gerente = new javax.swing.JLabel();
        lbl_regimen = new javax.swing.JLabel();
        lbl_resolucion_fact = new javax.swing.JLabel();
        lbl_promedio_ventas_diaria = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbl_nit_empresa = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbl_promedio_ventas_mensual = new javax.swing.JLabel();
        lbl_fecha_resolucion = new javax.swing.JLabel();
        lbl_facturacion_desde = new javax.swing.JLabel();
        lbl_facturacion_hasta = new javax.swing.JLabel();
        lbl_factura_actual = new javax.swing.JLabel();
        lbl_valor_inventario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("MI EMPRESA"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Empresa:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Correo:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Gerente:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Regimen:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Res. Facturacion:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Nit:");

        lbl_nombre_empresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nombre_empresa.setText("................................");

        lbl_correo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_correo.setText("................................");

        lbl_gerente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_gerente.setText("................................");

        lbl_regimen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_regimen.setText("................................");

        lbl_resolucion_fact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_resolucion_fact.setText("................................");

        lbl_promedio_ventas_diaria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_promedio_ventas_diaria.setText("................................");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("Fecha:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Desde:");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Hasta:");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Ult Factura:");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Prom. Ventas D:");

        lbl_nit_empresa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nit_empresa.setText("................................");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("Prom. Ventas M:");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Valor Inventario:");

        lbl_promedio_ventas_mensual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_promedio_ventas_mensual.setText("................................");

        lbl_fecha_resolucion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_fecha_resolucion.setText("................................");

        lbl_facturacion_desde.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_facturacion_desde.setText("................................");

        lbl_facturacion_hasta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_facturacion_hasta.setText("................................");

        lbl_factura_actual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_factura_actual.setText("................................");

        lbl_valor_inventario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_valor_inventario.setText("................................");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(56, 56, 56)
                        .addComponent(lbl_nombre_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68)
                        .addComponent(lbl_correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(62, 62, 62)
                        .addComponent(lbl_gerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(57, 57, 57)
                        .addComponent(lbl_regimen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(lbl_resolucion_fact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_promedio_ventas_diaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(92, 92, 92)
                        .addComponent(lbl_nit_empresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(16, 16, 16)
                        .addComponent(lbl_promedio_ventas_mensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(73, 73, 73)
                        .addComponent(lbl_fecha_resolucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(71, 71, 71)
                        .addComponent(lbl_facturacion_desde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(74, 74, 74)
                        .addComponent(lbl_facturacion_hasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(44, 44, 44)
                        .addComponent(lbl_factura_actual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(17, 17, 17)
                        .addComponent(lbl_valor_inventario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_nombre_empresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_correo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_gerente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_regimen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lbl_resolucion_fact))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(lbl_fecha_resolucion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lbl_facturacion_desde))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lbl_facturacion_hasta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lbl_factura_actual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(lbl_promedio_ventas_diaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lbl_promedio_ventas_mensual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(lbl_valor_inventario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lbl_nit_empresa))
                .addGap(13, 13, 13))
        );

        jLabel8.setText("SWIN Desarrollo de Software");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_factura_actual;
    private javax.swing.JLabel lbl_facturacion_desde;
    private javax.swing.JLabel lbl_facturacion_hasta;
    private javax.swing.JLabel lbl_fecha_resolucion;
    private javax.swing.JLabel lbl_gerente;
    private javax.swing.JLabel lbl_nit_empresa;
    private javax.swing.JLabel lbl_nombre_empresa;
    private javax.swing.JLabel lbl_promedio_ventas_diaria;
    private javax.swing.JLabel lbl_promedio_ventas_mensual;
    private javax.swing.JLabel lbl_regimen;
    private javax.swing.JLabel lbl_resolucion_fact;
    private javax.swing.JLabel lbl_valor_inventario;
    // End of variables declaration//GEN-END:variables
}
